// Curated and Cloudinary high-resolution project images
import heroHome from './images/christmas_crochet_hero_1789759469203.jpg';
import catProjects from './images/cat_projects_1789759486379.jpg';
import catBlankets from './images/cat_blankets_1789759497658.jpg';
import article1Hero from './images/article1_hero_1789759507918.jpg';
import article2Hero from './images/article2_hero_1789759637527.jpg';
import article3Hero from './images/article3_hero_1789759520113.jpg';
import article4Hero from './images/article4_hero_1789759648974.jpg';

export const projectImages = {
  // 1 to 32 exact matching Cloudinary images for Article 1
  bauble: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767380/Crochet_Christmas_Bauble_Ornaments_Rustic_Vintage.jpg',
  snowflake: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767365/Crochet_Snowflake_Ornament_Classic_Victorian_Lace.jpg',
  treeOrnament: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767218/Crochet_Christmas_Tree_Ornament_Nordic_Minimalist.jpg',
  santaOrnament: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767373/Crochet_Santa_Claus_Ornament_Whimsical_Folk_Art.jpg',
  gingerbreadOrnament: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767361/Crochet_Gingerbread_Man_Ornament_Warm_Bakery_Charm.jpg',
  candyCane: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767241/Crochet_Striped_Candy_Cane_Traditional_Festive.jpg',
  stocking: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767237/Classic_Cable_Christmas_Stocking_Heritage_Craft.jpg',
  miniStocking: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767246/Mini_Crochet_Stockings_Garland_Cottagecore_Christmas.jpg',
  garland: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767245/Crochet_Christmas_Pine_Garland_Botanical_Farmhouse.jpg',
  wreath: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789767188/Crochet_Holiday_Door_Wreath_Modern_Botanical.jpg',
  miniTree: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770500/Tabletop_Bobble_Christmas_Trees_Scandinavian_Hygge.jpg',
  snowman: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770350/Cozy_Crochet_Snowman_Figure_Playful_Winter_Folk.jpg',
  reindeer: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770491/Rustic_Crochet_Reindeer_Amigurumi_Woodland_Holiday.jpg',
  santaAmigurumi: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770362/Crochet_Santa_Amigurumi_Doll_Classic_Victorian_Santa.jpg',
  elf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770496/Festive_Holiday_Elf_Doll_Whimsical_Fantasy.jpg',
  gingerbreadMan: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770483/Crochet_Gingerbread_Man_Softie_Warm_Confectionery.jpg',
  mugCozy: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770415/Holiday_Cocoa_Mug_Cozy_Cozy_Morning_Cabin.jpg',
  coaster: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770416/Peppermint_Snowflake_Coasters_Festive_Retro.jpg',
  treeSkirt: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770363/Chunky_Waffle_Christmas_Tree_Skirt_Modern_Farmhouse_Luxury.jpg',
  tableRunner: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770325/Festive_Lace_Table_Runner_Timeless_Heirloom.jpg',
  pillow: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770219/Cabled_Holiday_Throw_Pillow_Chalet_Luxe.jpg',
  wallHanging: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770147/Holiday_Tapestry_Wall_Hanging_Modern_Minimalist.jpg',
  giftBag: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770152/Reusable_Crochet_Gift_Pouches_Eco_Holiday_Craft.jpg',
  giftBasket: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770198/Chunky_Holiday_Storage_Basket_Modern_Rustic.jpg',
  hat: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770174/Santa_Beanie_with_Faux_Fur_Pom_Cozy_Holiday_Wearable.jpg',
  scarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789770092/Textured_Holiday_Chevron_Scarf_Winter_Classic.jpg',
  potholder: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789769996/Double-Thick_Christmas_Potholders_Homestead_Kitchen.jpg',
  towel: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789769911/Waffle_Stitch_Kitchen_Hand_Towel_Boutique_Spa_Farmhouse.jpg',
  bell: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789769909/Hanging_Door_Knob_Bell_Bauble_Vintage_Americana.jpg',
  star: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789769875/Dimensional_Crochet_Holiday_Star_Scandinavian_Woodcraft.jpg',
  pineCone: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789769917/Crochet_Pine_Cone_Ornament_Naturalist_Evergreen.jpg',
  gingerbreadHouse: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789769898/Crochet_Gingerbread_House_Ornament_Confectionery_Keepsake.jpg',
};

// 25 exact matching Cloudinary images for Quick & Easy Projects (Article 2)
export const quickProjectImages = {
  rusticGiftTags: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804476/1_Five-Minute_Rustic_Gift_Tags_Eco_Farmhouse.jpg',
  ribbonCandy: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804475/Flat_Ribbon_Candy_Ornament_Old_Fashioned_Confection.jpg',
  cinnamonStickTree: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804473/Modern_Cinnamon_Stick_Tree_Botanical_Craft.jpg',
  peppermintKeychain: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804473/Peppermint_Swirl_Keychain_Retro_Graphic.jpg',
  lipBalmPocket: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804470/Festive_Lip_Balm_Pocket_Keychain.jpg',
  wineBottleSweater: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804470/Crochet_Wine_Bottle_Sweater_Collar.jpg',
  hotCocoaSleeve: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804469/Quick_Hot_Cocoa_Cup_Sleeve.jpg',
  scandiStarGarland: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804468/Flat_Scandinavian_Star_Garland.jpg',
  masonJarCozy: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804468/Crochet_Mason_Jar_Tea_Light_Cozy.jpg',
  fingerlessMitts: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789804469/Cozy_Crochet_Fingerless_Mitts.jpg',
  jingleBellStockings: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805233/Miniature_Jingle_Bell_Stockings.jpg',
  gingerbreadCoaster: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805234/Crochet_Gingerbread_House_Coaster.jpg',
  poinsettiaBrooch: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805232/Quick_Poinsettia_Flower_Brooch.jpg',
  snowflakeBookmark: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805226/Crochet_Snowflake_Bookmark.jpg',
  pomPomTree: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805225/Chunky_Pom-Pom_Tree_Ornament.jpg',
  soapSaverPouch: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805225/Holiday_Soap_Saver_Pouch.jpg',
  reindeerCupCozy: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805225/Reindeer_Face_Cup_Cozy.jpg',
  candyCanePenCozy: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805219/Crochet_Candy_Cane_Pen_Cozy.jpg',
  grannySquareTree: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805225/Granny_Square_Holiday_Tree_Ornament.jpg',
  snowmanBottleTopper: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805208/Crochet_Snowman_Bottle_Topper.jpg',
  velvetHeadband: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805208/Scalloped_Velvet_Holiday_Headband.jpg',
  gingerbreadStarGarland: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805207/Crochet_Gingerbread_Star_Garland.jpg',
  candleRing: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805205/Crochet_Holiday_Candle_Ring.jpg',
  petCollar: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805206/Crochet_Jingle_Bell_Collar_for_Pets.jpg',
  santaHatHairClip: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789805203/Miniature_Santa_Hat_Hair_Clip.jpg'
};

// Exact matching Cloudinary images for Blankets (Article 3)
export const blanketImages = {
  heirloomGranny: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807750/Heirloom_Christmas_Granny_Square_Blanket.jpg',
  candyCaneStriped: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807745/Festive_Candy_Cane_Striped_Blanket.jpg',
  santaBeltBuckle: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807741/Santa_Claus_Belt_Buckle_Afghan.jpg',
  embossedSnowflake: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807757/Embossed_Snowflake_Motif_Blanket.jpg',
  pineForestBobble: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807757/Pine_Forest_Bobble_Christmas_Blanket.jpg',
  nordicFairIsle: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807750/Nordic_Fair_Isle_Christmas_Throw.jpg',
  buffaloPlaid: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807736/Buffalo_Plaid_Tartan_Christmas_Blanket.jpg',
  peppermintSwirl: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807757/Red_White_Peppermint_Swirl_Afghan.jpg',
  victorianPoinsettia: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807734/Vintage_Victorian_Poinsettia_Throw.jpg',
  chunkyVelvet: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807742/Chunky_Velvet_Holiday_Throw.jpg',
  festiveBabyBlanket: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807733/Festive_Holiday_Baby_Blanket.jpg',
  thermalWaffle: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807733/Cozy_Winter_Thermal_Waffle_Afghan.jpg',
  hearthLapBlanket: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807733/Holiday_Hearth_Lap_Blanket.jpg',
  chunkyCableChalet: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789807728/Chunky_Cable_Winter_Chalet_Blanket.jpg',
  botanicalThrow: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789810693/Sage_Green_Cream_Botanical_Throw.jpg',
  heritageFringe: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789810696/Heritage_Christmas_Afghan_with_Fringe.jpg',
  c2cTreeBlanket: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789810693/C2C_Christmas_Tree_Blanket.jpg',
  retroGraphgan: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789810691/Retro_Christmas_Graphgan_Throw.jpg',
  nordicMosaic: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789810697/Nordic_Mosaic_Christmas_Blanket.jpg',
  samplerStitch: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789810681/Holiday_Sampler_Stitch_Afghan.jpg',
  colorblockThrow: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789810683/Modern_Minimalist_Colorblock_Throw.jpg',
};

// 15 exact matching Cloudinary images for Beginner Blankets (Article 4)
export const beginnerBlanketImages = {
  holidayLinen: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811612/The_Holiday_Linen_Moss_Stitch_Blanket.jpg',
  grannyStripe: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811612/Classic_Christmas_Granny_Stripe_Blanket.jpg',
  giantGrannySquare: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811612/Continuous_Giant_Holiday_Granny_Square.jpg',
  simpleVStitch: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811605/Simple_Holiday_V-Stitch_Afghan.jpg',
  hdcRibbed: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811603/Cozy_Half_Double_Crochet_Ribbed_Throw.jpg',
  threeStripeChunky: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811602/Three-Stripe_Holiday_Chunky_Blanket.jpg',
  gentleRipple: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811603/Gentle_Ripple_Christmas_Lapghan.jpg',
  peppermintRound: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811601/Peppermint_Swirl_Round_Baby_Blanket.jpg',
  lemonPeel: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811599/Textured_Lemon_Peel_Holiday_Throw.jpg',
  ginghamPlaid: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811589/Farmhouse_Gingham_Plaid_Afghan.jpg',
  modernGridGranny: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811587/Modern_Grid_Granny_Square_Blanket.jpg',
  c2cSolidThrow: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811585/Holiday_Corner-to-Corner_C2C_Solid_Throw.jpg',
  cornerTasseled: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811586/Easy_Holiday_Corner-Tasseled_Blanket.jpg',
  candyStripeRipple: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811583/Candy_Stripe_Ripple_Blanket.jpg',
  samplerStripe: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789811583/One-Skein-at-a-Time_Holiday_Sampler_Stripe.jpg',
};

// 42 scarf images for Article 5 (real Cloudinary URLs)
export const scarfImages = {
  heroScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903088/Chunky_Ribbed_Scarf.jpg',
  easyChunkyRibbed: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903088/Chunky_Ribbed_Scarf.jpg',
  grannyStripeScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903088/Granny_Stripe_Scarf.jpg',
  seedStitchScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903089/Seed_Stitch_Scarf_2.jpg',
  mossStitchLightweight: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903058/Moss_Stitch_Lightweight_Scarf.jpg',
  hdcRibbedScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903070/Half_Double_Crochet_Ribbed_Scarf.jpg',
  superBulkyQuick: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903067/Super_Bulky_Quick_Scarf_2.jpg',
  vStitchLacy: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903062/V-Stitch_Lacy_Scarf.jpg',
  texturedBobble: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903053/extured_Bobble_Scarf.jpg',
  delicateLacyOneSkein: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903058/Delicate_Lacy_One-Skein_Scarf.jpg',
  quickRibbedNeckWarmer: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903038/Quick_Ribbed_Neck_Warmer.jpg',
  simpleGarterLook: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903038/Simple_Garter-Look_Scarf.jpg',
  oneSkeinSeedStitch: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903026/One-Skein_Seed_Stitch_Scarf.jpg',
  grannyStripeOneSkein: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902995/Granny_Stripe_One-Skein_Scarf.jpg',
  chainSCMinimal: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902985/Chain_and_SC_Minimal_Scarf.jpg',
  classicTopDownTriangle: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902977/Classic_Top-Down_Triangle_Scarf.jpg',
  asymmetricTriangle: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902951/Asymmetric_Triangle_Scarf.jpg',
  grannySquareTriangleShawl: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789903026/Granny_Square_Triangle_Shawl.jpg',
  topDownCrescentShawl: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902935/Top-Down_Crescent_Shawl.jpg',
  sideToSideTriangle: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902956/Side-to-Side_Triangle_Scarf.jpg',
  bohemianFringedTriangle: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902950/Bohemian_Fringed_Triangle.jpg',
  oversizedTriangleWrap: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902871/Oversized_Triangle_Wrap.jpg',
  classicBeginnerInfinity: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902837/Classic_Beginner_Infinity_Scarf.jpg',
  chunkyInfinityCowl: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902919/Chunky_Infinity_Cowl.jpg',
  seedStitchInfinity: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902833/Seed_Stitch_Infinity_Scarf.jpg',
  mobiusTwistInfinity: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902910/Mobius_Twist_Infinity_Scarf.jpg',
  twoColorStripedInfinity: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902867/Two-Color_Striped_Infinity_Scarf.jpg',
  ribbedInfinityCowl: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902869/Ribbed_Infinity_Cowl.jpg',
  laceInfinityScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902870/Lace_Infinity_Scarf.jpg',
  beginnerHoodedScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902826/Beginner_Hooded_Scarf.jpg',
  chunkyWinterHooded: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902822/Chunky_Winter_Hooded_Scarf.jpg',
  lacyHoodedScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902809/Lacy_Hooded_Scarf.jpg',
  stripedHoodedScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902829/Striped_Hooded_Scarf.jpg',
  ribbedHoodedScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902759/Ribbed_Hooded_Scarf.jpg',
  hoodedCowlScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902752/Hooded_Cowl_Scarf.jpg',
  beginnerScarfWithSleeves: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902765/Beginner_Scarf_With_Sleeves.jpg',
  wearableBlanketScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902761/Wearable_Blanket_Scarf.jpg',
  scarfShrugHybrid: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902709/Scarf_Shrug_Hybrid.jpg',
  redGreenHolidayScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902576/Red_and_Green_Holiday_Scarf.jpg',
  candyCaneStripeScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902724/Candy_Cane_Stripe_Scarf.jpg',
  nordicColorworkScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902564/Nordic_Colorwork_Scarf.jpg',
  holidayGiftSetScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902576/Holiday_Gift_Set_Scarf.jpg',
  festiveSparkleScarf: 'https://res.cloudinary.com/dhkyla1rv/image/upload/v1789902530/Festive_Sparkle_Scarf.jpg',
};

export const siteImages = {
  heroHome,
  catProjects: projectImages.wreath,
  catBlankets: blanketImages.heirloomGranny,
  article1Hero: projectImages.wreath,
  article2Hero: quickProjectImages.rusticGiftTags,
  article3Hero: blanketImages.chunkyCableChalet,
  article4Hero: beginnerBlanketImages.holidayLinen,
  
  // Specific projects mapped to user's high-definition Cloudinary assets
  bauble: projectImages.bauble,
  snowflake: projectImages.snowflake,
  treeOrnament: projectImages.treeOrnament,
  santaOrnament: projectImages.santaOrnament,
  gingerbreadOrnament: projectImages.gingerbreadOrnament,
  candyCane: projectImages.candyCane,
  stocking: projectImages.stocking,
  miniStocking: projectImages.miniStocking,
  garland: projectImages.garland,
  wreath: projectImages.wreath,
  miniTree: projectImages.miniTree,
  snowman: projectImages.snowman,
  reindeer: projectImages.reindeer,
  santaAmigurumi: projectImages.santaAmigurumi,
  elf: projectImages.elf,
  gingerbreadMan: projectImages.gingerbreadMan,
  mugCozy: projectImages.mugCozy,
  coaster: projectImages.coaster,
  treeSkirt: projectImages.treeSkirt,
  tableRunner: projectImages.tableRunner,
  pillow: projectImages.pillow,
  wallHanging: projectImages.wallHanging,
  giftBag: projectImages.giftBag,
  giftBasket: projectImages.giftBasket,
  hat: projectImages.hat,
  scarf: projectImages.scarf,
  potholder: projectImages.potholder,
  towel: projectImages.towel,
  bell: projectImages.bell,
  star: projectImages.star,
  pineCone: projectImages.pineCone,
  gingerbreadHouse: projectImages.gingerbreadHouse,
};
